<?php require("view/header.phtml");?>
<link rel="stylesheet" type="text/css" href="assets/css/icons.css">
<link rel="stylesheet" type="text/css" href="assets/css/style.css">


<body>
  <div class="background">
  <svg class="clouds cloud1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0" y="0" width="512" height="512" viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve">
    <path id="cloud-icon" d="M406.1 227.63c-8.23-103.65-144.71-137.8-200.49-49.05 -36.18-20.46-82.33 3.61-85.22 45.9C80.73 229.34 50 263.12 50 304.1c0 44.32 35.93 80.25 80.25 80.25h251.51c44.32 0 80.25-35.93 80.25-80.25C462 268.28 438.52 237.94 406.1 227.63z"/>
	</svg>
  <svg class="clouds cloud2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0" y="0" width="512" height="512" viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve">
    <path id="cloud-icon" d="M406.1 227.63c-8.23-103.65-144.71-137.8-200.49-49.05 -36.18-20.46-82.33 3.61-85.22 45.9C80.73 229.34 50 263.12 50 304.1c0 44.32 35.93 80.25 80.25 80.25h251.51c44.32 0 80.25-35.93 80.25-80.25C462 268.28 438.52 237.94 406.1 227.63z"/>
	</svg>
  <div class="container">
  <form action="generatecsv.php" method="post">
  <ul class="input-list style-2 clearfix">
    <li>
      <input type="text" id="date_from"name="date_from"class="date_time" placeholder="10/04/2016 10:00:00" maxlength="19">
    </li>
    <li>
      <input type="text" id="date_to"name="date_to"class="date_time" placeholder="16/10/2016 10:00:00" maxlength="19">
    </li>
    <input type="submit" onmouseup="send()"/>
    <input type="hidden" name="sensor_id" id="sensor_id" value="<?php echo $result->getId();?>"/>
  </ul>



    Creating history file for <?php echo $result->getName();?><br>
    <span>download not starting automatically?<span>

    <div id="button-wrap-inner">
          <a class="btn" href="">download</a>
    </div>


<script src="https://code.jquery.com/jquery-2.1.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.9/jquery.mask.js"></script>
<script>
$(document).ready(function(){
  $('.date').mask('00/00/0000');
  $('.time').mask('00:00:00');
  $('.date_time').mask('00-00-0000 00:00:00');
  $('.cep').mask('00000-000');
  $('.phone').mask('0000-0000');
  $('.phone_with_ddd').mask('(00) 0000-0000');
  $('.phone_us').mask('(000) 000-0000');
  $('.mixed').mask('AAA 000-S0S');
  $('.cpf').mask('000.000.000-00', {reverse: true});
  $('.cnpj').mask('00.000.000/0000-00', {reverse: true});
  $('.money').mask('000.000.000.000.000,00', {reverse: true});
  $('.money2').mask("#.##0,00", {reverse: true});
  $('.ip_address').mask('0ZZ.0ZZ.0ZZ.0ZZ', {
    translation: {
      'Z': {
        pattern: /[0-9]/, optional: true
      }
    }
  });
  $('.ip_address').mask('099.099.099.099');
  $('.percent').mask('##0,00%', {reverse: true});
  $('.clear-if-not-match').mask("00/00/0000", {clearIfNotMatch: true});
  $('.placeholder').mask("00/00/0000", {placeholder: "__/__/____"});
  $('.fallback').mask("00r00r0000", {
      translation: {
        'r': {
          pattern: /[\/]/,
          fallback: '/'
        },
        placeholder: "__/__/____"
      }
    });
  $('.selectonfocus').mask("00/00/0000", {selectOnFocus: true});
});
</script>
<script>
function send() {
    // get values
    var date_from  = $("#date_from").val();
    var date_to = $("#date_to").val();
    var sensor_id = $("#sensor_id").val();
        $.post("generatecsv.php", {
            date_from:date_from,
            date_to: date_to,
            sensor_id:sensor_id
        }, function (data, status) {
          console.log(data);
        });

}
</script>
