
<link href='http://fonts.googleapis.com/css?family=Roboto:100,300,700,400' rel='stylesheet' type='text/css'>
<meta name="viewport" content="width=device-width">
<!--<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.4/themes/flick/jquery-ui.css">-->
<link rel="stylesheet" type="text/css" href="assets/css/jquery-ui-slider-pips.css">
<link rel="stylesheet" type="text/css" href="https://simeydotme.github.io/jQuery-ui-Slider-Pips/dist/css/app.min.css">
<link rel="stylesheet" type="text/css" href="https://simeydotme.github.io/jQuery-ui-Slider-Pips/dist/css/jqueryui.min.css">

<link rel="stylesheet" type="text/css" href="assets/css/app.css">
<nav class="navBar">
		<div class="logo"><a href="/"><img class="logimg"src="/assets/img/home.svg" alt="home"></a></div>
    <div class="logo"><a href="setpoint.php"><img class="logimg"src="/assets/img/radiator.svg" alt="home"></a></div>
</nav>
<?php date_default_timezone_set('Europe/London');?>
